spring:
  cloud:
    gateway:
      routes:
        - id: msvc-courses
          uri: lb://courses-service
          predicates:
            - Path=/api/courses/**
          filters:
            - StripPrefix=2
        - id: msvc-users
          uri: lb://users-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2